// List of sample S&P 500 / Global companies for autocomplete
const companiesList = [
    { name: "Apple Inc.", ticker: "AAPL" },
    { name: "Microsoft Corp.", ticker: "MSFT" },
    { name: "Alphabet Inc.", ticker: "GOOGL" },
    { name: "Amazon.com Inc.", ticker: "AMZN" },
    { name: "NVIDIA Corp.", ticker: "NVDA" },
    { name: "Tesla Inc.", ticker: "TSLA" },
    { name: "Meta Platforms Inc.", ticker: "META" },
    { name: "Berkshire Hathaway", ticker: "BRK.B" },
    { name: "UnitedHealth Group", ticker: "UNH" },
    { name: "Johnson & Johnson", ticker: "JNJ" },
    { name: "JPMorgan Chase & Co.", ticker: "JPM" },
    { name: "Visa Inc.", ticker: "V" },
    { name: "Procter & Gamble", ticker: "PG" },
    { name: "Mastercard Inc.", ticker: "MA" },
    { name: "Home Depot", ticker: "HD" },
    { name: "Chevron Corp.", ticker: "CVX" },
    { name: "AbbVie Inc.", ticker: "ABBV" },
    { name: "Eli Lilly & Co.", ticker: "LLY" },
    { name: "Merck & Co.", ticker: "MRK" },
    { name: "Coca-Cola Co.", ticker: "KO" },
    { name: "PepsiCo Inc.", ticker: "PEP" },
    { name: "Broadcom Inc.", ticker: "AVGO" },
    { name: "Pfizer Inc.", ticker: "PFE" },
    { name: "Walmart Inc.", ticker: "WMT" },
    { name: "Costco Wholesale", ticker: "COST" },
    { name: "Walt Disney Co.", ticker: "DIS" },
    { name: "McDonald's Corp.", ticker: "MCD" },
    { name: "Abbott Laboratories", ticker: "ABT" },
    { name: "Danaher Corp.", ticker: "DHR" },
    { name: "Toyota Motor Corp.", ticker: "TM" },
    { name: "Sony Group Corp.", ticker: "SONY" },
    { name: "Samsung Electronics", ticker: "SSNLF" },
    { name: "Tencent Holdings", ticker: "TCEHY" }
];
